import Head from "next/head";
import { useEffect, useState } from "react";
import BigArticle from "../components/BigArticle";
import SmallArticle from "../components/SmallArticle";
import MediumArticle from "../components/MediumArticle";
import articles from "../data/articles.json";

export default function Home() {
  const [imageData, setImageData] = useState([]);

  async function fetchImageData() {
    const response = await fetch("https://picsum.photos/v2/list");
    const data = await response.json();

    return data;
  }

  useEffect(() => {
    (async () => {
      const imageData = await fetchImageData();
      setImageData(imageData);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>ZIARUL DE ASII</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-12 px-16 gap-12">
        {/* aici ar trebui sa vina Headerul facut de Andreea */}
        <div className="col-span-8 flex gap-16">
          {articles.map(
            (article, index) =>
              index < 2 && (
                <BigArticle
                  key={`bigArticle-${article.title}-${index}`}
                  title={article.title}
                  description={article.description}
                  articleHref={article.articleHref}
                  imageSrc={imageData[index]?.download_url}
                />
              )
          )}
        </div>
        <div className="col-span-4 flex flex-col gap-12">
          {articles.map(
            (article, index) =>
              index < 3 && (
                <SmallArticle
                  key={`smallArticle-${article.title}-${index}`}
                  title={article.title}
                  description={article.description}
                  articleHref={article.articleHref}
                />
              )
          )}
        </div>
        <div className="col-span-12 flex flex-row justify-between items-center">
          <h5 className="font-bold text-4xl text-indigo-900">
            The science behind Smart UV
          </h5>

          <a
            href={"#"}
            className="text-slate-900 text-lg font-medium border-2 border-purple-700 rounded-xl w-fit px-8 py-1"
          >
            See all articles
          </a>
        </div>
        <div className="col-span-12 flex flex-row gap-6">
          {articles.slice(4).map((article, index) => {
            return (
              <MediumArticle
                key={`mediumArticle-firstRow-${article.title}-${index}`}
                title={article.title}
                description={article.description}
                articleHref={article.articleHref}
                imageSrc={imageData[index]?.download_url}
              />
            );
          })}
        </div>
        {/* Inca o sectiune cu articole */}
        <div className="col-span-12 flex flex-row justify-between items-center">
          <h5 className="font-bold text-4xl text-indigo-900">
            Smart UV case studies
          </h5>

          <a
            href={"#"}
            className="text-slate-900 text-lg font-medium border-2 border-purple-700 rounded-xl w-fit px-8 py-1"
          >
            See all articles
          </a>
        </div>
        <div className="col-span-12 flex flex-row gap-6">
          {articles.slice(4).map((article, index) => {
            return (
              <MediumArticle
                key={`mediumArticle-secondRow-${article.title}-${index}`}
                title={article.title}
                description={article.description}
                articleHref={article.articleHref}
                imageSrc={imageData[index]?.download_url}
              />
            );
          })}
        </div>
      </main>
    </>
  );
}
